export const colors = {
  "base-white": "#ffffff",
  "base-black": "#000000",
  "base-yellow": "#fbcf6d",
  "base-cyan": "#35d4dd",
  "base-magenta": "#d368c8",

  "accent-lighter-yellow": "#f9dc9a",
  "accent-darker-yellow": "#fdc33f",
  "accent-darkest-yellow": "#ffb612",
  "accent-lighter-cyan": "#77d8dd",
  "accent-darker-cyan": "#2db2ba",
  "accent-darkest-cyan": "#279ca3",
  "accent-eerie-black": "#1a1a1a",
  "accent-offblack": "#303030",
  "accent-ash-gray": "#4d4d4d",
  "accent-squant": "#666666",
  "accent-uniform-grey": "#a8a8a8",
  "accent-quick-silver": "#c4c4c4",
  "accent-alto": "#e0e0e0",
  "accent-offwhite": "#f9f9f9",

  "system-warning-red": "#ff0000",
  "system-success-green": "#229c20",
  "system-caution-orange": "#ff8c00",
  "system-caution-yellow": "#ffb61d",
  "system-cloud-blue": "#d5e0ed",
  "system-link-blue": "#1e90ff",
  "system-navy-blue": "#4d81ce",
};
